# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mailtable',
            name='user',
        ),
        migrations.AddField(
            model_name='mailtable',
            name='mail',
            field=models.CharField(default='def', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtable',
            name='sender',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtable',
            name='subject',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailtable',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
