# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20160512_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtable',
            name='mail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailtable',
            name='sender',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mailtable',
            name='subject',
            field=models.TextField(),
        ),
    ]
