# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_auto_20160512_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtable',
            name='subject',
        ),
    ]
