# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_remove_mailtable_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtable',
            name='subject',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
