# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTable',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=200)),
                ('subject', models.TextField()),
                ('mail', models.TextField()),
            ],
        ),
    ]
